#!/bin/ash

export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

mount -t proc proc /proc
mount -n -t sysfs /sys /sys
mount -n -o remount,rw /
#mount -o mode=0755 -t tmpfs none /dev
#/bin/mknod /dev/console c 5 1
/bin/mknod /dev/null c 1 3
/bin/mknod /dev/zero c 1 5
/bin/mkdir /dev/pts
/bin/mkdir /dev/shm
mount -n -t devpts /dev/pts /dev/pts
echo  /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

[ ! -d /mnt/flash ]  && mkdir /mnt/flash
mount -t jffs2 /dev/mtdblock5 /mnt/flash
if [ $? -ne 0 ]; then
	echo -n "Can't mount config partition, format now?(y/n)"
	read action
	if [ $action = "y" ]; then
		flash_eraseall -j /dev/mtd5
		mount -t jffs2 /dev/mtdblock5 /mnt/flash
	else
		exit 1
	fi
	
fi

[ ! -d /mnt/flash/rc.d ] && mkdir /mnt/flash/rc.d
[ ! -d /mnt/flash/config ] && mkdir /mnt/flash/config

ln -s /mnt/flash/rc.d /etc/rc.d
ln -s /mnt/flash/config /etc/config

adduser admin -D -h /home/admin
echo admin:admin | chpasswd

/usr/local/sbin/config-vlan.sh 3 LLLLW
ip link set eth2 name eth100
vconfig add eth100 1
vconfig add eth100 2
ip link set eth100.1 name eth0
ip link set eth100.2 name eth1
ifconfig  eth100 up
echo 1 > /proc/sys/net/ipv4/ip_forward

[ ! -d /var/run ] && mkdir /var/run
[ ! -d /var/log ] && mkdir /var/log

ubusd &
syslogd
systemd -d
devman -d
lighttpd -f /etc/lighttpd/lighttpd.conf 
for file in /etc/rc.d/* ; do 
	if [ -x $file ] ; then
		$file
	fi
done 

